---
title: "Data Wrangling Report"
output: html_document
---

### Data Wrangling Report

```{r}
df_raw <- read_excel( "New_York_City_Restaurants.xlsx", 
                      col_types = c(rep("text", 8), 
                                    "date", 
                                    rep("text", 4), 
                                    "numeric",
                                    "text",
                                    rep("date", 2),
                                    "text"))
```


```{r}
tame_df <- function ( df_raw ) {
  
  df_raw %>% 
    clean_names() %>% 
    # Rename variables
    rename(id = camis, rest_name = dba, cuisine_descr = cuisine_description,
           violation_descr = violation_description) %>% 
    # Inspection date: Ignore values "1900-01_01"
    mutate(inspection_date = ymd(inspection_date)) %>% 
    filter(!(inspection_date == "1900-01-01")) %>%
    # convert 'cuisine description' into factor
    mutate(cuisine_descr = as_factor(cuisine_descr)) %>% 
    # Cuisine_description: Relabel level "Café/Coffee/Tea" and "Latin (...
    mutate(cuisine_descr = 
             fct_recode(cuisine_descr, 
                        Coffee_Tea = "Café/Coffee/Tea",
                        Latin = "Latin (Cuban, Dominican, Puerto Rican, South & Central American)")) %>% 
    # only keep the 20 most frequent cuisines    
    mutate(cuisine_descr = fct_lump(f = cuisine_descr, n = 20)) %>% 
    # Boro: recode missing values and convert into factor
    mutate(boro = na_if(boro, "Missing")) %>% 
    mutate(boro = as_factor(boro)) %>% 
    # Actions taken: convert into a factor and (re)name its levels
    mutate(action = as_factor(action)) %>% 
    mutate(action = 
             fct_recode(action, 
                        YesViol = "Violations were cited in the following area(s).",
                        ReOpened = "Establishment re-opened by DOHMH",
                        Closed = "Establishment Closed by DOHMH.
                        Violations were cited in the following area(s)
                        and those requiring immediate action were addressed.",
                        ReClosed = "Establishment re-closed by DOHMH",
                        NoViol = "No violations were recorded at the time of this inspection.")) %>% 
    # Convert 'violation_code' into factor
    # mutate(violation_code = as_factor(violation_code)) %>% 
    # Violation types: new variable violation_group
    mutate(violation_group = case_when(
      violation_code %in% str_c("02", LETTERS[1:10]) ~ "food_temperature",
      violation_code %in% c(str_c("03", LETTERS[1:7]), str_c("09", LETTERS[1:3])) ~ "food_source",
      violation_code %in% str_c("04", LETTERS[1:10]) ~ "food_protection",
      violation_code %in% c(str_c("05", LETTERS[1:9]), str_c("10", LETTERS[1:10])) ~ "facility",
      violation_code %in% str_c("06", LETTERS[1:9]) ~ "hygiene",
      violation_code %in% str_c("04", LETTERS[11:15]) ~ "vermin",
      violation_code %in% c("07A", "99B") ~ "other_scored",
      !is.na(violation_code) ~ "not_scored"
    )) %>% 
    # Create indicator variables for levels of 'violation_group'
    mutate(viol_vermin = case_when(violation_group == "vermin" ~ 1, TRUE ~ 0),
           viol_not_scored = case_when(violation_group == "not_scored" ~ 1, TRUE ~ 0),
           viol_facility = case_when(violation_group == "facility" ~ 1, TRUE ~ 0),
           viol_food_temperature = case_when(violation_group == "food_temperature" ~ 1, TRUE ~ 0),
           viol_hygiene = case_when(violation_group == "hygiene" ~ 1, TRUE ~ 0),
           viol_food_protection = case_when(violation_group == "food_protection" ~ 1, TRUE ~ 0),
           viol_food_source = case_when(violation_group == "food_source" ~ 1, TRUE ~ 0),
           viol_other_scored = case_when(violation_group == "other_scored"  ~ 1, TRUE ~ 0)
    ) %>% 
    # Inspection type: collapse into fewer categories
    separate(inspection_type, into = c("before_slash", "after_slash"), sep = " / ") %>% 
    mutate(after_slash = str_replace_all(after_slash, fixed(" "), fixed(""))) %>% 
    mutate(inspection_type2 = str_replace_all(after_slash, fixed("-i"), fixed("I"))) %>% 
    # Indicator variable for level 'Initial Inspection'
    mutate(dummy_InitialInspection = case_when(
      inspection_type2 == "InitialInspection" ~ "Initial",
      TRUE ~ "Not_Initial"
    )) %>%
    # mutate(dummy_InitialInspection = as_factor(dummy_InitialInspection)) %>% 
    # Grade: Recode NA's with inspection type = 'InitialInspection' and 'score' > 14 to "Not Yet Graded"
    mutate(grade = case_when(
      is.na(.$grade) &
        .$inspection_type2 == "InitialInspection" &
        .$score > 14 ~ "Not Yet Graded",
      TRUE ~ grade
    )) 
  
}
```

```{r}
df_tame <- tame_df()
```


```{r}
# Save clean data frame to RDS file
saveRDS(df_tame, "df_tame.rds")
```




  
  


  
  
  
  
  
  

